# Generated by Django 2.2.2 on 2019-07-06 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='listing-images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='logo',
            field=models.ImageField(blank=True, upload_to='listing-logo/'),
        ),
    ]
