# Generated by Django 2.2.2 on 2001-01-01 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20190706_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['company_name'], 'verbose_name': 'listing_list'},
        ),
    ]
