# Generated by Django 2.2.2 on 2019-07-08 03:03

from django.db import migrations
import django_countries.fields
import listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_auto_20010101_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={},
        ),
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=django_countries.fields.CountryField( max_length=2),
        ),
    ]
