# Generated by Django 2.2.2 on 2019-07-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_auto_20190708_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='country',
            field=models.CharField(choices=[('DZ', 'Algeria'), ('AO', 'Angola'), ('BJ', 'Benin'), ('BW', 'Botswana'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CM', 'Cameroon'), ('CV', 'Cape Verde'), ('CF', 'Central African Republic'), ('KM', 'Comoros'), ('CD', 'Democratic Republic of Congo'), ('DJ', 'Djibouti'), ('EG', 'Egypt'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'), ('ET', 'Ethiopia'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GH', 'Ghana'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('CI', 'Ivory Coast'), ('KE', 'Kenya'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('ML', 'Mali'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('NA', 'Namibia'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('CG', 'Republic of the Congo'), ('RE', 'Reunion'), ('RW', 'Rwanda'), ('SH', 'Saint Helena'), ('ST', 'Sao Tome and Principe'), ('SN', 'Senegal'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone')], max_length=200),
        ),
    ]
