# Generated by Django 2.2.2 on 2019-07-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20190708_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='images',
        ),
        migrations.AlterField(
            model_name='listing',
            name='logo',
            field=models.ImageField(upload_to='listing-logo/'),
        ),
    ]
