# Generated by Django 2.2.2 on 2019-07-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_listing_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='products',
            new_name='tags',
        ),
    ]
