# Generated by Django 2.2.2 on 2001-01-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_auto_20190710_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='motto',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
