# Generated by Django 2.2.2 on 2001-01-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_auto_20010101_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='category',
            new_name='segment',
        ),
    ]
