# Generated by Django 2.2.2 on 2001-01-01 00:08

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_auto_20010101_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.Listing_category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Products(separate with comma'),
        ),
    ]
