# Generated by Django 2.2.2 on 2001-01-01 00:12

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0016_auto_20010101_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='segment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='listing.Listing_category', verbose_name='Business category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Products(separate with comma)'),
        ),
    ]
