# Generated by Django 2.2.2 on 2019-07-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0017_auto_20010101_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='terms',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
