# Generated by Django 2.2.2 on 2019-07-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0018_auto_20190714_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='terms',
            field=models.CharField(choices=[('yes', 'Yes')], default=1, max_length=50, verbose_name='I agree to Terms and Conditions)'),
        ),
    ]
