# Generated by Django 2.2.2 on 2001-01-01 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0020_auto_20010101_0003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing_category',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category'},
        ),
        migrations.RemoveField(
            model_name='listing',
            name='segment',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listing.Category'),
        ),
    ]
