# Generated by Django 2.1.7 on 2019-06-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_commentmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentManager',
        ),
    ]
