# Generated by Django 2.2.2 on 2001-01-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20190611_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
