country_choice ={
'Algeria':	'Algeria',
'Angola':	'Angola',
'Benin':	'Benin',
'Botswana':	'Botswana',
'Burkina Faso':	'Burkina Faso',
'Burundi':	'Burundi',
'Cameroon':	'Cameroon',
'Cape Verde':	'Cape Verde',
'Central African Republic':	'Central African Republic',
'Comoros':	'Comoros',
'Democratic Republic of Congo':	'Democratic Republic of Congo',
'Djibouti':	'Djibouti',
'Egypt':	'Egypt',
'Equatorial Guinea':	'Equatorial Guinea',
'Eritrea':	'Eritrea',
'Ethiopia':	'Ethiopia',
'Gabon':	'Gabon',
'Gambia':	'Gambia',
'Ghana':	'Ghana',
'Guinea':	'Guinea',
'Guinea-Bissau':	'Guinea-Bissau',
'Ivory Coast':	'Ivory Coast',
'Kenya':	'Kenya',
'Lesotho':	'Lesotho',
'Liberia':	'Liberia',
'Libya':	'Libya',
'Madagascar':	'Madagascar',
'Malawi':	'Malawi',
'Mali':	'Mali',
'Mauritania':	'Mauritania',
'Mauritius':	'Mauritius',
'Morocco':	'Morocco',
'Mozambique':	'Mozambique',
'Namibia':	'Namibia',
'Niger':	'Niger',
'Nigeria':	'Nigeria',
'Republic of the Congo':	'Republic of the Congo',
'Reunion':	'Reunion',
'Rwanda':	'Rwanda',
'Saint Helena':	'Saint Helena',
'Sao Tome and Principe':	'Sao Tome and Principe',
'Senegal':	'Senegal',
'Seychelles':	'Seychelles',
'Sierra Leone':	'Sierra Leone',

}
