# Generated by Django 2.2.2 on 2019-07-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20010101_0153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
