# Generated by Django 2.2.2 on 2019-07-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
