# Generated by Django 2.2.2 on 2001-01-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
