# Generated by Django 2.2.2 on 2001-01-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='email',
            new_name='S_email',
        ),
    ]
