# Generated by Django 2.2.2 on 2019-07-03 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_auto_20190702_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(max_length=250)),
            ],
            options={
                'verbose_name': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='upload/'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
