# Generated by Django 2.2.2 on 2019-07-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_auto_20190703_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='blockquote1',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='blockquote2',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='blockquote3',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='blockquote4',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='blockquote5',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
