# Generated by Django 2.2.2 on 2019-07-04 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0012_auto_20190704_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
