# Generated by Django 2.2.2 on 2019-07-04 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0013_article_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
    ]
