# Generated by Django 2.2.2 on 2019-07-06 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Article', '0014_auto_20190704_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.Article')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_ranking', to='contenttypes.ContentType')),
            ],
        ),
    ]
