# Generated by Django 2.2.2 on 2019-07-06 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0016_auto_20190706_0012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
