# Generated by Django 2.2.2 on 2001-01-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0018_article_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='link_name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
