# Generated by Django 2.2.2 on 2001-01-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0019_auto_20010101_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
