# Generated by Django 2.2.2 on 2019-07-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0020_auto_20010101_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='part1',
            field=models.CharField(blank=True, choices=[('true', 'True'), ('false', 'False')], max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='part2',
            field=models.CharField(blank=True, choices=[('true', 'True'), ('false', 'False')], max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='part3',
            field=models.CharField(blank=True, choices=[('true', 'True'), ('false', 'False')], max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='part4',
            field=models.CharField(blank=True, choices=[('true', 'True'), ('false', 'False')], max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='part5',
            field=models.CharField(blank=True, choices=[('true', 'True'), ('false', 'False')], max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
